//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResolverEcuacionCuadratica.Test.Wcf.SICuadratica {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SICuadratica.IResolverEcuacionCuadratica")]
    public interface IResolverEcuacionCuadratica {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResolverEcuacionCuadratica/ResolverLaEcuacionCuadratica", ReplyAction="http://tempuri.org/IResolverEcuacionCuadratica/ResolverLaEcuacionCuadraticaRespon" +
            "se")]
        ResolverEcuacionCuadratica.Test.Wcf.SICuadratica.ResolverLaEcuacionCuadraticaResponse ResolverLaEcuacionCuadratica(ResolverEcuacionCuadratica.Test.Wcf.SICuadratica.ResolverLaEcuacionCuadraticaRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResolverEcuacionCuadratica/ResolverLaEcuacionCuadratica", ReplyAction="http://tempuri.org/IResolverEcuacionCuadratica/ResolverLaEcuacionCuadraticaRespon" +
            "se")]
        System.Threading.Tasks.Task<ResolverEcuacionCuadratica.Test.Wcf.SICuadratica.ResolverLaEcuacionCuadraticaResponse> ResolverLaEcuacionCuadraticaAsync(ResolverEcuacionCuadratica.Test.Wcf.SICuadratica.ResolverLaEcuacionCuadraticaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResolverLaEcuacionCuadratica", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ResolverLaEcuacionCuadraticaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public double primerNumero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public double segundoNumero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public double tercerNumero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public double primeraRaiz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public double segundaRaiz;
        
        public ResolverLaEcuacionCuadraticaRequest() {
        }
        
        public ResolverLaEcuacionCuadraticaRequest(double primerNumero, double segundoNumero, double tercerNumero, double primeraRaiz, double segundaRaiz) {
            this.primerNumero = primerNumero;
            this.segundoNumero = segundoNumero;
            this.tercerNumero = tercerNumero;
            this.primeraRaiz = primeraRaiz;
            this.segundaRaiz = segundaRaiz;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResolverLaEcuacionCuadraticaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ResolverLaEcuacionCuadraticaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public double primeraRaiz;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public double segundaRaiz;
        
        public ResolverLaEcuacionCuadraticaResponse() {
        }
        
        public ResolverLaEcuacionCuadraticaResponse(double primeraRaiz, double segundaRaiz) {
            this.primeraRaiz = primeraRaiz;
            this.segundaRaiz = segundaRaiz;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IResolverEcuacionCuadraticaChannel : ResolverEcuacionCuadratica.Test.Wcf.SICuadratica.IResolverEcuacionCuadratica, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResolverEcuacionCuadraticaClient : System.ServiceModel.ClientBase<ResolverEcuacionCuadratica.Test.Wcf.SICuadratica.IResolverEcuacionCuadratica>, ResolverEcuacionCuadratica.Test.Wcf.SICuadratica.IResolverEcuacionCuadratica {
        
        public ResolverEcuacionCuadraticaClient() {
        }
        
        public ResolverEcuacionCuadraticaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResolverEcuacionCuadraticaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResolverEcuacionCuadraticaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResolverEcuacionCuadraticaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ResolverEcuacionCuadratica.Test.Wcf.SICuadratica.ResolverLaEcuacionCuadraticaResponse ResolverEcuacionCuadratica.Test.Wcf.SICuadratica.IResolverEcuacionCuadratica.ResolverLaEcuacionCuadratica(ResolverEcuacionCuadratica.Test.Wcf.SICuadratica.ResolverLaEcuacionCuadraticaRequest request) {
            return base.Channel.ResolverLaEcuacionCuadratica(request);
        }
        
        public void ResolverLaEcuacionCuadratica(double primerNumero, double segundoNumero, double tercerNumero, ref double primeraRaiz, ref double segundaRaiz) {
            ResolverEcuacionCuadratica.Test.Wcf.SICuadratica.ResolverLaEcuacionCuadraticaRequest inValue = new ResolverEcuacionCuadratica.Test.Wcf.SICuadratica.ResolverLaEcuacionCuadraticaRequest();
            inValue.primerNumero = primerNumero;
            inValue.segundoNumero = segundoNumero;
            inValue.tercerNumero = tercerNumero;
            inValue.primeraRaiz = primeraRaiz;
            inValue.segundaRaiz = segundaRaiz;
            ResolverEcuacionCuadratica.Test.Wcf.SICuadratica.ResolverLaEcuacionCuadraticaResponse retVal = ((ResolverEcuacionCuadratica.Test.Wcf.SICuadratica.IResolverEcuacionCuadratica)(this)).ResolverLaEcuacionCuadratica(inValue);
            primeraRaiz = retVal.primeraRaiz;
            segundaRaiz = retVal.segundaRaiz;
        }
        
        public System.Threading.Tasks.Task<ResolverEcuacionCuadratica.Test.Wcf.SICuadratica.ResolverLaEcuacionCuadraticaResponse> ResolverLaEcuacionCuadraticaAsync(ResolverEcuacionCuadratica.Test.Wcf.SICuadratica.ResolverLaEcuacionCuadraticaRequest request) {
            return base.Channel.ResolverLaEcuacionCuadraticaAsync(request);
        }
    }
}
